export default {
  GET_ARTICLES: 'GET_ARTICLES',
  GET_ARTICLES_FAILURE: 'GET_ARTICLES_FAILURE',
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',

  SET_ACTIVE_ARTICLE: 'SET_ACTIVE_ARTICLE',

  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
}