export default {
  GET_ARTICLES: 'GET_ARTICLES',
  GET_ARTICLES_FAILURE: 'GET_ARTICLES_FAILURE',
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',

  REFRESH_ARTICLES: 'REFRESH_ARTICLES',

  SET_ACTIVE_ARTICLE: 'SET_ACTIVE_ARTICLE',

  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
}